- hosts: all
  become: yes
  gather_facts: no
  become_user: admin
  tasks:

  - name: create table in BQ
    shell: |
        bq mk -t {{ dataset_name }}.{{ table_name }} name:STRING,salary:FLOAT,DOB:STRING
