- hosts: all
  become: yes
  gather_facts: no
  become_user: admin
  tasks:

  - name: load data and truncate data
    shell: |
        bq --location=us load --source_format=CSV --autodetect sample_dataset1.Household gs://testin_bucket/Household-living-costs-price-indexes-September-2022-quarter-group-facts.csv
        bq query --use_legacy_sql=false 'select count(*) from ht-xl-357708.sample_dataset1.Household'
        bq query --use_legacy_sql=false 'truncate table ht-xl-357708.sample_dataset1.Household'
        bq query --use_legacy_sql=false 'select count(*) from ht-xl-357708.sample_dataset1.Household'