- hosts: all
  become: yes
  gather_facts: no
  become_user: root
  - name: Installing postgresql
    shell: | 
      sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list'
      wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
      apt-get update
      apt-get install -y postgresql postgresql-contrib
      systemctl start postgresql.service
      psql --version
