- name: install docker
  hosts: all
  become: yes
  - name: Install dependencies
    apt:
      name: "{{ item }}"
      state: present
    with_items:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
  
  - name: Add Docker GPG key
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present
  
  - name: Add Docker APT repository
    apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable
      state: present
  
  - name: Install Docker CE
    apt:
      name: docker-ce
      state: present
  
  - name: Add root user to docker group
    user:
      name: root
      append: yes
      groups: docker
  
  - name: Add user to docker group
    user:
      name: abinitio
      append: yes
      groups: docker
